export enum HookFlag {
	ALL_HOOK_MASK = 14,
	BEFORE_INITIALIZE = 13,
	AFTER_INITIALIZE = 12,
	BEFORE_ADD_LIQUIDITY = 11,
	AFTER_ADD_LIQUIDITY = 10,
	BEFORE_REMOVE_LIQUIDITY = 9,
	AFTER_REMOVE_LIQUIDITY = 8,
	BEFORE_SWAP = 7,
	AFTER_SWAP = 6,
	BEFORE_DONATE = 5,
	AFTER_DONATE = 4,
	BEFORE_SWAP_RETURNS_DELTA = 3,
	AFTER_SWAP_RETURNS_DELTA = 2,
	AFTER_ADD_LIQUIDITY_RETURNS_DELTA = 1,
	AFTER_REMOVE_LIQUIDITY_RETURNS_DELTA = 0,
}


